### ISSUE TITLE
Simulation error when simulating Egg model

### ISSUE THREAD

**Issue by tayloris** [equinor/flownet#109]
This error is encounter by running Egg model. No simulation file is generated, so the error appear before any OPM model is created.

This error comes first:

```
Running MDA ES for 1  iterations	1.0
Running MDA ES on (weights normalized)	1.0
The script 'ExternalErtScript' caused an error while running:
Traceback (most recent call last):
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/bin/flownet_save_iteration_parameters", line 11, in <module>
    load_entry_point('flownet', 'console_scripts', 'flownet_save_iteration_parameters')()
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/ahm/_assisted_history_matching.py", line 275, in save_iteration_parameters
    compression="gzip",
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 2369, in to_parquet
    **kwargs,
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/lib/python3.6/site-packages/pandas/io/parquet.py", line 95, in write
    self.validate_dataframe(df)
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/lib/python3.6/site-packages/pandas/io/parquet.py", line 58, in validate_dataframe
    raise ValueError("parquet must have string column names")
ValueError: parquet must have string column names
Saving ERT parameters to file... 
```

And later this error apears

```
Simulations failed with the following error: Simulation failed! All realizations failed!
Traceback (most recent call last):
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/ahm/_assisted_history_matching.py", line 131, in run_ert
    check=True,
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'export PYTHONWARNINGS=ignore::DeprecationWarning;ert es_mda --weights '1' ahm_config.ert' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/bin/flownet", line 11, in <module>
    load_entry_point('flownet', 'console_scripts', 'flownet')()
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/_command_line.py", line 206, in main
    args.func(args)
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/_command_line.py", line 67, in flownet_ahm
    run_flownet_history_matching(config, args)
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/ahm/_run_ahm.py", line 405, in run_flownet_history_matching
    ahm.run_ert(weights=config.ert.ensemble_weights)
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/ahm/_assisted_history_matching.py", line 141, in run_ert
    raise RuntimeError(pathlib.Path(error_files[0]).read_text())
RuntimeError: <error>
  <time>12:47:09</time>
  <job>CREATE_FLOWNET_MODEL</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/venv/bin/flownet_render_realization", line 11, in <module>
    load_entry_point('flownet', 'console_scripts', 'flownet_render_realization')()
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/realization/_render_realization.py", line 146, in render_realization
    args.random_samples, parameters, args.realization_index
  File "/home/manuel/repos/projects/Flownet_August2020/flownet/src/flownet/realization/_render_realization.py", line 46, in _ert_samples2simulation_input
    list(unsorted_random_samples.keys()), key=lambda x: int(x.split("_")[0])
AttributeError: 'float' object has no attribute 'keys'
</stderr>
  <stderr_file>/home/manuel/repos/projects/Flownet_August2020/flownet/output_egg/output/runpath/realization-3/iter-0/CREATE_FLOWNET_MODEL.stderr.0</stderr_file>
</error>
```

**Comment by tayloris** [comment]
It appears to fail when it try to create a flow model.

**Comment by wouterjdb** [comment]
With some digging it turns out that this is a bug originating from the update in configsuite (#88) which makes these lines not do what they are supposed to do:

https://github.com/equinor/flownet/blob/57b10f02f967b050289b7cfe447b2d5d88cbba48/src/flownet/ahm/_run_ahm.py#L211-L214

Previously, this made sure that if gas parameters for the relative permeability were not supplied they would not be created as uncertain parameters. Now, with the new configsuite version, `None` never happens as all parameters will always be a `NamedDict` but the subitems will all be `None`.

This was not caught because we only test on the Norne case which has both oil and gas fully defined.
