### ISSUE TITLE
Webviz failing: cannot import name 'ALL'

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#113]
```
ImportError: cannot import name 'ALL'
Traceback (most recent call last):
  File "/home/media-unix/flownet/venv/bin/flownet", line 33, in <module>
    sys.exit(load_entry_point('flownet', 'console_scripts', 'flownet')())
  File "/home/media-unix/flownet/src/flownet/_command_line.py", line 206, in main
    args.func(args)
  File "/home/media-unix/flownet/src/flownet/_command_line.py", line 70, in flownet_ahm
    create_webviz(args.output_folder, start_webviz=args.start_webviz)
  File "/home/media-unix/flownet/src/flownet/_command_line.py", line 32, in create_webviz
    check=True,
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
```

**Comment by anders-kiaer** [comment]
This does not happen under CI right? What are the steps to reproduce? My guess is something with the Python environment.

**Comment by wouterjdb** [comment]
Reproduce it by running the Norne AHM test locally.

**Comment by anders-kiaer** [comment]
Solved by updating `dash` Python dependency locally - closing as it is not an issue with FlowNet.

**Comment by anders-kiaer** [comment]
Upstream issue: https://github.com/equinor/webviz-subsurface/issues/401
