### ISSUE TITLE
All simulations failed

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/flownet#300]
When I run, in the Brugge test case,
`flownet ahm config/assisted_history_matching.yml ./output/`
after intialization, every "Running forecast for iteration: 0" fails, getting at the end the following error:
```
Simulations failed with the following error: Simulation failed! All realizations failed!
Traceback (most recent call last):
  File "/home/riccardo/.local/bin/flownet", line 11, in <module>
    load_entry_point('flownet', 'console_scripts', 'flownet')()
  File "/home/riccardo/Desktop/flownet/src/flownet/_command_line.py", line 274, in main
    args.func(args)
  File "/home/riccardo/Desktop/flownet/src/flownet/_command_line.py", line 69, in flownet_ahm
    run_flownet_history_matching(config, args)
  File "/home/riccardo/Desktop/flownet/src/flownet/ahm/_run_ahm.py", line 787, in run_flownet_history_matching
    ahm.run_ert(weights=config.ert.ensemble_weights)
  File "/home/riccardo/Desktop/flownet/src/flownet/ahm/_assisted_history_matching.py", line 116, in run_ert
    runpath=self._config.ert.runpath,
  File "/home/riccardo/Desktop/flownet/src/flownet/ert/_run_subprocess.py", line 65, in run_ert_subprocess
    pathlib.Path(error_files[0]).read_text()
subprocess.SubprocessError: <error>
  <time>11:59:25</time>
  <job>COPY_FILE</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File "/home/riccardo/.local/share/ert/shell_scripts/copy_file", line 3, in <module>
    from res.fm.shell import copy_file
ImportError: No module named res.fm.shell
</stderr>
  <stderr_file>/home/riccardo/Documents/main_project/data/flownet-testdata-master/brugge/output/output/runpath/realization-179/iter-0/copy_file.stderr.1</stderr_file>
</error>

```

**Comment by wouterjdb** [comment]
These errors are not inside the FlowNet source code but in ERT/libres code.

Which versions of libres (res), libecl (ecl) and ERT are installed?

**Comment by Riccardopeli** [comment]
ECL 2.9.4
ert 2.17.1
equinor-libres: 7.2.0

**Comment by wouterjdb** [comment]
> ECL 2.9.4
> ert 2.17.1
> equinor-libres: 7.2.0

That is the exact same as what I have.

As the error indicates Python has problems importing the model `res.fm.shell`. I suspect that - for some reason unknown to me at this moment - during runtime your virtual environment isn't properly sourced.

How are you running FlowNet? You should run it via your command line like so:

`flownet ahm <config> <output_folder>`

**Comment by Riccardopeli** [comment]
I reinstalled Flownet in a fresh virtual environment and now the test cases successfully run.
I am running flownet via:
`flownet ahm <config> <output_folder>`
Thank you for the help
