### ISSUE TITLE
More useful error output

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/flownet#34]
When all/too many realizations fail you now get:
```
Simulations failed with the following error: Simulation failed! All realizations failed!
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.9/bin/flownet", line 8, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/flownet/_command_line.py", line 100, in main
    run_flownet_history_mathing(config, args)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/flownet/_run_ahm.py", line 306, in run_flownet_history_mathing
    ahm.run_ert(mode="es_mda", weights=config.ert.ensemble_weights)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/flownet/_assisted_history_matching.py", line 336, in run_ert
    check=True,
  File "/opt/python/3.6.9/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'export PYTHONWARNINGS=ignore::DeprecationWarning;ert es_mda --weights '1' ahm_config.ert' returned non-zero exit status 1.
The command "flownet ../tests/configs/norne_parameters.yml ./some_ert_setup" exited with 1.
```

Would be useful that the subprocess command does show the actual error message from ERT. And if that is not informative either, either change Flownet or ERT to show e.g. stderr from the job that is failing in the realizations.

**Comment by wouterjdb** [comment]
Hasn't #76 already solved this @anders-kiaer?

**Comment by anders-kiaer** [comment]
Yes 💪🏻
